"""empty message

Revision ID: 2b9a6bfc5f61
Revises: 
Create Date: 2020-01-29 18:22:13.276552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9a6bfc5f61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Actor', ['name'])
    op.create_unique_constraint(None, 'Movie', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Movie', type_='unique')
    op.drop_constraint(None, 'Actor', type_='unique')
    # ### end Alembic commands ###
