"""empty message

Revision ID: 8a373459d4fe
Revises: 2b9a6bfc5f61
Create Date: 2020-01-29 18:35:20.772830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a373459d4fe'
down_revision = '2b9a6bfc5f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Movie', 'release_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Movie', 'release_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
